Profile: DiagnosticReportLab
Parent: DiagnosticReport
Id: DiagnosticReportLab
Description: "This profile represents the set of information related to the Laboratory diagnosis report generated by the laboratory services like Complete Blood Count, Basic Metabolic Panel, Lipid Panel, Urinalysis, etc. are ordered for the patient."
* ^meta.versionId = "1"
* ^meta.lastUpdated = "2023-11-01T04:23:55.19535+00:00"
* ^version = "6.0.0"
* ^status = #draft
* ^date = "2020-08-17T08:04:42.1502332Z"
* ^publisher = "National Resource Center for EHR Standards"
* ^contact.telecom.system = #url
* ^contact.telecom.value = "http://nrces.in/"
* ^jurisdiction = urn:iso:std:iso:3166#IN
* basedOn only Reference(NutritionOrder or MedicationRequest or ServiceRequest or CarePlan or ImmunizationRecommendation)
* basedOn MS
* status MS
* category MS
* category.coding MS
* category.coding.system 1..
* category.coding.system = "http://snomed.info/sct" (exactly)
* category.coding.code 1..
* category.coding.display 1..
* category.text MS
* code MS
* code.coding MS
* code.coding.system 1..
* code.coding.system = "http://loinc.org" (exactly)
* code.coding.code 1..
* code.coding.display 1..
* code.text MS
* subject only Reference(Group or Device or Location or Patient)
* encounter only Reference(Encounter)
* performer only Reference(CareTeam or Organization or Practitioner or PractitionerRole)
* performer MS
* resultsInterpreter 1.. MS
* resultsInterpreter only Reference(CareTeam or Practitioner or Organization or PractitionerRole)
* specimen only Reference(Specimen)
* specimen MS
* result 1.. MS
* result only Reference(Observation)
* imagingStudy only Reference(ImagingStudy)
* media.link only Reference(Media)
* conclusion 1.. MS
* conclusionCode MS
* conclusionCode.coding MS
* conclusionCode.coding.system 1..
* conclusionCode.coding.system = "http://snomed.info/sct" (exactly)
* conclusionCode.coding.code 1..
* conclusionCode.coding.display 1..
* conclusionCode.text MS
* presentedForm.contentType 1..
* presentedForm.data 1..